### DISCUSSION TITLE
Manera alternativa para mostrar el informe textual

### DISCUSSION THREAD

**Discussion by mrngomez** [uvejota/homeassistant-edata#180] [Tarjetas y configuraciones alternativas]
Hola.

En la documentación se recomienda, para visualizar todos los atributos del sensor, el siguiente método:

<details>
  <summary>Markdown</summary>

```
type: markdown
content: >
  {% for attr in states.sensor.edata_xxxx.attributes %} {%- if not
  attr=="friendly_name" and not attr=="unit_of_measurement"  and not
  attr=="icon" -%} **{{attr}}**: {{state_attr("sensor.edata_xxxx", attr)}} {{-
  '\n' -}} {%- endif %} {%- endfor -%}
title: Informe
```
</details>

Que da como resultado la siguiente tarjeta:

<details>
  <summary>Tarjeta original</summary>
  <img src="https://github.com/uvejota/homeassistant-edata/assets/25464952/e27eccde-9268-4639-9a5a-c2c0e58801bf">
</details>

Quería proponer una alternativa más visual, que estoy usando en mi instancia de HASS. Únicamente depende de la extensión multiple-entity-row

https://github.com/benct/lovelace-multiple-entity-row

A continuación, adjunto los fragmentos de código que he creado a tal efecto.

El siguiente YAML muestra todos los atributos disponibles a través del sensor:

<details>
  <summary>YAML completo</summary>

```
type: entities
entities:
  - entity: sensor.edata_br1p
    name: CUPS
    icon: mdi:identifier
    type: custom:multiple-entity-row
    attribute: cups
  - entity: sensor.edata_br1p
    name: Término de potencia
    icon: mdi:meter-electric-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: contract_p1_kW
        name: Potencia pico (P1)
        unit: kW
        format: precision3
      - attribute: contract_p2_kW
        name: Potencia valle (P2)
        unit: kW
        format: precision3
  - entity: sensor.edata_br1p
    name: Última actualización
    icon: mdi:calendar-end-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: last_registered_date
        format: datetime
  - entity: sensor.edata_br1p
    name: Consumo ayer (kWh)
    icon: mdi:calendar-today-outline
    type: custom:multiple-entity-row
    show_state: false
    unit: kWh
    state_header: total
    entities:
      - attribute: yesterday_p1_kWh
        name: Punta
      - attribute: yesterday_p2_kWh
        name: Llano
      - attribute: yesterday_p3_kWh
        name: Valle
      - attribute: yesterday_kWh
        name: Total
  - entity: sensor.edata_br1p
    name: Consumo último (kWh)
    icon: mdi:calendar-week-begin-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: last_registered_day_kWh
        name: total
      - attribute: last_registered_day_p1_kWh
        name: Punta
      - attribute: last_registered_day_p2_kWh
        name: Llano
      - attribute: last_registered_day_p3_kWh
        name: Valle
      - attribute: last_registered_day_hours
        name: horas
        hide_if: 24
  - entity: sensor.edata_br1p
    name: Consumo mes
    icon: mdi:calendar-month
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: month_€
        name: Coste
        unit: €
      - attribute: month_kWh
        name: Total
        unit: kWh
      - attribute: month_daily_kWh
        name: Media
        unit: kWh/dia
      - attribute: month_days
        name: Dias
  - entity: sensor.edata_br1p
    name: Mes por franjas (kWh)
    icon: mdi:calendar-multiselect
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: month_p1_kWh
        name: Pico
      - attribute: month_p2_kWh
        name: Llano
      - attribute: month_p3_kWh
        name: Valle
  - entity: sensor.edata_br1p
    name: Mes pasado
    icon: mdi:calendar-month-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: last_month_€
        name: Coste
        unit: €
      - attribute: last_month_kWh
        name: Total
        unit: kWh
      - attribute: last_month_daily_kWh
        name: Media
        unit: kWh/dia
      - attribute: last_month_days
        name: Dias
  - entity: sensor.edata_br1p
    name: Mes pasado franjas (kWh)
    icon: mdi:calendar-multiselect-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: last_month_p1_kWh
        name: Pico
      - attribute: last_month_p2_kWh
        name: Llano
      - attribute: last_month_p3_kWh
        name: Valle
  - entity: sensor.edata_br1p
    name: Fecha maxímetro
    icon: mdi:calendar-plus-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: max_power_date
        format: datetime
  - entity: sensor.edata_br1p
    name: Maxímetro (kW)
    icon: mdi:lightning-bolt-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: max_power_kW
        name: Máximo consumo
      - attribute: max_power_mean_kW
        name: Media
      - attribute: max_power_90perc_kW
        name: 90%

```
</details>
<details>
  <summary>tarjeta completa</summary>
  <img src="https://github.com/uvejota/homeassistant-edata/assets/25464952/f5b6dbf0-95ef-4978-b516-0f5e3898986b">
</details>

Este YAML es un subconjunto del anterior, es el que uso en mi panel principal.

<details>
  <summary>YAML reducido</summary>

```
type: entities
entities:
  - entity: sensor.edata_br1p
    name: Última actualización
    icon: mdi:calendar-end-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: last_registered_date
        format: datetime
  - entity: sensor.edata_br1p
    name: Consumo ayer (kWh)
    icon: mdi:calendar-today-outline
    type: custom:multiple-entity-row
    show_state: false
    unit: kWh
    state_header: total
    entities:
      - attribute: yesterday_p1_kWh
        name: Punta
      - attribute: yesterday_p2_kWh
        name: Llano
      - attribute: yesterday_p3_kWh
        name: Valle
      - attribute: yesterday_kWh
        name: Total
  - entity: sensor.edata_br1p
    name: Consumo último (kWh)
    icon: mdi:calendar-week-begin-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: last_registered_day_kWh
        name: total
      - attribute: last_registered_day_p1_kWh
        name: Punta
      - attribute: last_registered_day_p2_kWh
        name: Llano
      - attribute: last_registered_day_p3_kWh
        name: Valle
      - attribute: last_registered_day_hours
        name: horas
        hide_if: 24
  - entity: sensor.edata_br1p
    name: Consumo mes
    icon: mdi:calendar-month
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: month_€
        name: Coste
        unit: €
      - attribute: month_kWh
        name: Total
        unit: kWh
      - attribute: month_daily_kWh
        name: Media
        unit: kWh/dia
      - attribute: month_days
        name: Dias
  - entity: sensor.edata_br1p
    name: Mes pasado
    icon: mdi:calendar-month-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: last_month_€
        name: Coste
        unit: €
      - attribute: last_month_kWh
        name: Total
        unit: kWh
      - attribute: last_month_daily_kWh
        name: Media
        unit: kWh/dia
      - attribute: last_month_days
        name: Dias
  - entity: sensor.edata_br1p
    name: Fecha maxímetro
    icon: mdi:calendar-plus-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: max_power_date
        format: datetime
  - entity: sensor.edata_br1p
    name: Maxímetro (kW)
    icon: mdi:lightning-bolt-outline
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - attribute: max_power_kW
        name: Máximo consumo
      - attribute: max_power_mean_kW
        name: Media
      - attribute: max_power_90perc_kW
        name: 90%

```
</details>

<details>
  <summary>Tarjeta reducida</summary>
  <img src="https://github.com/uvejota/homeassistant-edata/assets/25464952/c81733bd-4268-4239-b5c1-0006a64ce95b">
</details>

Dejo esto aquí a modo de ayuda para alguien que quiera una manera distinta de mostrar la información que esta gran extensión nos permine extraer del portal de datadis (cuando vuelcan los datos).

Un saludo.
