### DISCUSSION TITLE
Cards actualizadas desde update 2024.07.4 (Compatible con version 2024.07.6)

### DISCUSSION THREAD

**Discussion by diegofrances** [uvejota/homeassistant-edata#262] [Tarjetas y configuraciones alternativas]
Dejo a continuación las cards con "apexcharts-card" y la última versión actualizada. Tan solo tenéis que sustituir las "xxxx" por los dígitos de vuestro CUPS.

![imagen](https://github.com/user-attachments/assets/bcf5ed70-cbf6-4b5e-ac5c-e1794d44a2ad)

<details><summary>Ayer</summary>
<p>

```
- type: custom:apexcharts-card
  chart_type: pie
  header:
    show: true
    title: Ayer
    show_states: true
    colorize_states: true
    floating: true
  all_series_config:
    unit: kWh
    show:
      legend_value: true
      in_header: false
  apex_config:
    chart:
      height: 250px
  series:
    - entity: sensor.xxxx_consumo_ayer
      show:
        in_chart: true
        in_header: true
      name: Total
    - entity: sensor.xxxx_consumo_ayer
      attribute: yesterday_p1_kWh
      name: Punta
    - entity: sensor.xxxx_consumo_ayer
      attribute: yesterday_p2_kWh
      name: Llano
    - entity: sensor.xxxx_consumo_ayer
      attribute: yesterday_p3_kWh
      name: Valle
``` 

<p>
</details>

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686e7948354443707a397834677a515764692f67697068792e676966](https://github.com/user-attachments/assets/3e557903-97d9-40ce-ac48-31e4d0d38bb7)

<details><summary>Consumo Diario</summary>
<p>

```
- type: custom:apexcharts-card
  graph_span: 30d
  stacked: true
  span:
    offset: '-1d'
  experimental:
    brush: true
  header:
    show: true
    title: Consumo diario
    show_states: false
    colorize_states: false
  brush:
    selection_span: 10d
  all_series_config:
    type: column
    unit: kWh
    show:
      legend_value: false
  series:
    - entity: sensor.edata_xxxx
      name: Total
      type: column
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/consumptions/daily',
        scups: 'xxxx'}).then(
            (resp) => {
                return resp.map((data, index) => {
                  return [new Date(data['datetime']).getTime(), data['value_kWh']];
                });
            }
        );
      show:
        in_chart: false
        in_brush: true
    - entity: sensor.edata_xxxx
      name: Punta
      stack_group: '1'
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/consumptions/daily',
        scups: 'xxxx'}).then(
            (resp) => {
                return resp.map((data, index) => {
                  return [new Date(data['datetime']).getTime(), data['value_p1_kWh']];
                });
            }
        );
    - entity: sensor.edata_xxxx
      name: Llano
      stack_group: '1'
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/consumptions/daily',
        scups: 'xxxx'}).then(
            (resp) => {
                return resp.map((data, index) => {
                  return [new Date(data['datetime']).getTime(), data['value_p2_kWh']];
                });
            }
        );
    - entity: sensor.edata_xxxx
      name: Valle
      stack_group: '1'
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/consumptions/daily',
        scups: 'xxxx'}).then(
            (resp) => {
                return resp.map((data, index) => {
                  return [new Date(data['datetime']).getTime(), data['value_p3_kWh']];
                });
            }
        );
```

</p>
</details>

![imagen](https://github.com/user-attachments/assets/647bcc1a-c701-47df-aacb-2964b2c08014)

<details><summary>Mes Actual</summary>
<p>

```
- type: custom:apexcharts-card
  chart_type: pie
  header:
    show: true
    title: Mes Actual
    show_states: true
    colorize_states: true
    floating: true
  all_series_config:
    show:
      legend_value: true
      in_header: false
    unit: kWh
  apex_config:
    chart:
      height: 250px
  series:
    - entity: sensor.xxxx_consumo_en_el_mes
      show:
        in_chart: false
        in_header: true
      name: Total
    - entity: sensor.xxxx_consumo_en_el_mes
      attribute: month_p1_kWh
      name: Punta
    - entity: sensor.xxxx_consumo_en_el_mes
      attribute: month_p2_kWh
      name: Llano
    - entity: sensor.xxxx_consumo_en_el_mes
      attribute: month_p3_kWh
      name: Valle
    - entity: sensor.xxxx_factura_del_mes
      name: Facturación
      show:
        in_chart: false
        in_header: true
      unit: €
```

</p>
</details>

![imagen](https://github.com/user-attachments/assets/3612a100-f78c-4fab-bcbb-a19a41532f33)

<details><summary>Último Mes</summary>
<p>

```
- type: custom:apexcharts-card
  chart_type: pie
  header:
    show: true
    title: Último Mes
    show_states: true
    colorize_states: true
    floating: true
  all_series_config:
    show:
      legend_value: true
      in_header: false
    unit: kWh
  apex_config:
    chart:
      height: 250px
  series:
    - entity: sensor.xxxx_consumo_durante_ultimo_mes
      show:
        in_chart: false
        in_header: true
      name: Total
    - entity: sensor.xxxx_consumo_durante_ultimo_mes
      attribute: last_month_p1_kWh
      name: Punta
    - entity: sensor.xxxx_consumo_durante_ultimo_mes
      attribute: last_month_p2_kWh
      name: Llano
    - entity: sensor.xxxx_consumo_durante_ultimo_mes
      attribute: last_month_p3_kWh
      name: Valle
    - entity: sensor.xxxx_factura_del_ultimo_mes
      name: Facturación
      show:
        in_chart: false
        in_header: true
      unit: €
```

</p>
</details> 

![imagen](https://github.com/user-attachments/assets/cc43f70e-a9f8-45d9-9e08-b52f3b0d3964)

<details><summary>Consumo Mensual</summary>
<p>

```
- type: custom:apexcharts-card
  graph_span: 395d
  stacked: true
  yaxis:
    - id: eje
      opposite: false
      max: '|+20|'
      min: ~0
      apex_config:
        forceNiceScale: true
  header:
    show: true
    title: Consumo mensual
    show_states: false
    colorize_states: false
  all_series_config:
    type: column
    yaxis_id: eje
    unit: kWh
    extend_to: false
    show:
      legend_value: false
  series:
    - entity: sensor.edata_xxxx
      type: line
      name: Total
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/ws/consumptions',
        scups: 'xxxx',
        aggr: 'month',
        records: 12});
      show:
        in_chart: true
    - entity: sensor.edata_xxxx
      name: Punta
      stack_group: '1'
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/ws/consumptions',
        scups: 'xxxx',
        aggr: 'month',
        tariff: 'p1',
        records: 12});
    - entity: sensor.edata_xxxx
      name: Llano
      stack_group: '1'
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/ws/consumptions',
        scups: 'xxxx',
        aggr: 'month',
        tariff: 'p2',
        records: 12});
    - entity: sensor.edata_xxxx
      name: Valle
      stack_group: '1'
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/ws/consumptions',
        scups: 'xxxx',
        aggr: 'month',
        tariff: 'p3',
        records: 12});
```

</p>
</details> 

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f754374366b716a37584e354b33504e346d452f67697068792e676966](https://github.com/user-attachments/assets/3b6de829-eed8-4432-ad9a-2bbd6ca3e37d)

<details><summary>Maxímetro</summary>
<p>

```
- type: custom:apexcharts-card
  graph_span: 1y
  span:
    offset: '-15d'
  header:
    show: true
    title: Maxímetro
    show_states: false
    colorize_states: false
  chart_type: scatter
  series:
    - entity: sensor.edata_xxxx
      type: column
      extend_to: false
      name: Punta
      show:
        extremas: true
        datalabels: false
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/ws/maximeter',
        tariff: 'p1',
        scups: 'xxxx'});
    - entity: sensor.edata_xxxx
      type: column
      extend_to: false
      name: Llano y Valle
      show:
        extremas: true
        datalabels: false
      data_generator: |
        return hass.connection.sendMessagePromise({
        type: 'edata/ws/maximeter',
        tariff: 'p2',
        scups: 'xxxx'});
```

</p>
</details>

Espero que os sirvan.
