### ISSUE TITLE
Agregar dos Cups

### ISSUE THREAD

**Issue by xboxtreme** [uvejota/homeassistant-edata#24]
Buenas, tengo dos sumunistros electricos, ¿podria agregar dos cups a la integracion?
He probado a añadir otra linea cups en configuration.yaml pero me da error

**Comment by uvejota** [comment]
Hola, sí que se debe poder añadir dos CUPS, del siguiente modo:

``` yaml
sensor:
  - platform: edata
    username: !secret my_datadis_username 
    password: !secret my_datadis_password 
    cups: !secret my_cups
  - platform: edata
    username: !secret my_datadis_username_2
    password: !secret my_datadis_password_2
    cups: !secret my_cups_2
```

igualmente, pueden pertenecer a la misma cuenta de datadis :-)
